version: "3.8"

services:
  db:
    image: postgres:15
    container_name: dev-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgressdata:/var/lib/postgresql/data
